package com.MediStock.app.utils;

import com.MediStock.app.entities.Notification;
import com.MediStock.app.enums.AlertType;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.List;

public class EmailTemplateBuilder {

    private EmailTemplateBuilder() {
    }

    public static String buildInventoryAlertEmail(List<Notification> notifications) {

        StringBuilder html = new StringBuilder();

        html.append("""
<!DOCTYPE html>
<html>

<head>

<style>

body{
font-family:Arial,sans-serif;
background:#F4F6F8;
padding:30px;
}

.container{
max-width:900px;
margin:auto;
background:white;
border-radius:12px;
overflow:hidden;
box-shadow:0 5px 20px rgba(0,0,0,.12);
}

.header{
background:#1976D2;
padding:28px;
color:white;
text-align:center;
}

.header h1{
margin:0;
font-size:32px;
}

.header p{
margin-top:8px;
font-size:15px;
}

.content{
padding:30px;
}

table{
width:100%;
border-collapse:collapse;
margin-top:20px;
}

th{
background:#1976D2;
color:white;
padding:14px;
}

td{
padding:12px;
border-bottom:1px solid #E5E7EB;
text-align:center;
}

.badge{
padding:6px 12px;
border-radius:20px;
font-weight:bold;
color:white;
display:inline-block;
}

.low{
background:#1976D2;
}

.expiring{
background:#ED6C02;
}

.expired{
background:#D32F2F;
}

.footer{
padding:20px;
text-align:center;
background:#F4F6F8;
color:#666;
font-size:13px;
}

</style>

</head>

<body>

<div class="container">

<div class="header">

<h1>💊 MediStock</h1>

<p>Pharmacy Inventory Management System</p>

</div>

<div class="content">

<h2>Inventory Alert Summary</h2>

<p>
The following inventory items require your attention.
</p>

<table>

<tr>

<th>Medicine</th>

<th>Category</th>

<th>Batch</th>

<th>Quantity</th>

<th>Expiry</th>

<th>Days Left</th>

<th>Alert</th>

<th>Recommended Action</th>

</tr>
""");

        DateTimeFormatter formatter =
                DateTimeFormatter.ofPattern("dd MMM yyyy");

        for (Notification notification : notifications) {

            AlertType type = notification.getAlertType();

            long daysRemaining =
                    ChronoUnit.DAYS.between(
                            LocalDate.now(),
                            notification.getInventory().getExpDate()
                    );

            String badge;

            String action;

            if (type == AlertType.LOW_STOCK) {

                badge =
                        "<span class='badge low'>LOW STOCK</span>";

                action =
                        "Restock Immediately";

            }

            else if (type == AlertType.EXPIRING_SOON) {

                badge =
                        "<span class='badge expiring'>EXPIRING SOON</span>";

                action =
                        "Use Existing Stock";

            }

            else {

                badge =
                        "<span class='badge expired'>EXPIRED</span>";

                action =
                        "Remove From Inventory";

            }

            html.append("<tr>");

            html.append("<td>")
                    .append(notification.getInventory().getMedicine().getName())
                    .append("</td>");

            html.append("<td>")
                    .append(notification.getInventory().getMedicine().getCategory())
                    .append("</td>");

            html.append("<td>")
                    .append(notification.getInventory().getBatchNumber())
                    .append("</td>");

            html.append("<td>")
                    .append(notification.getInventory().getQuantity())
                    .append("</td>");

            html.append("<td>")
                    .append(notification.getInventory().getExpDate().format(formatter))
                    .append("</td>");

            html.append("<td>")
                    .append(daysRemaining)
                    .append("</td>");

            html.append("<td>")
                    .append(badge)
                    .append("</td>");

            html.append("<td>")
                    .append(action)
                    .append("</td>");

            html.append("</tr>");

        }

        html.append("""
</table>

<br>

<p>

Please login to <b>MediStock</b> and resolve these inventory issues at the earliest.

</p>

</div>

<div class="footer">

This email was automatically generated by MediStock.

<br>

© 2026 MediStock. All Rights Reserved.

</div>

</div>

</body>

</html>
""");

        return html.toString();

    }

}